version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # image: localstack/localstack
    image: localstack/localstack:0.14.2
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4530:4510-4530"  # external services port range
      - "127.0.0.1:4571:4571"

    environment:
      - SERVICES=${SERVICES-}
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=local
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DISABLE_CORS_CHECK=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


  read-lyrics:
    image: read-lyrics
    ports:
      - "8080:8080"
    environment:
      DOCKER_ENV: true
    depends_on:
      - localstack


networks:
    default:
        name: localstack
        driver: bridge
