Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: /Users/naelsonmatheusjunior/repositories/HelloWorld-Lambda/HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: LOCALSTACK
          ENV_DOCKER: true